server:
  port: 9090
  servlet:
    context-path: /bootcamp

spring:
  datasource:
   driver-class-name: driver-class-name:org.postgressql.driver
   url: jdbc:postgresql://localhost:5432/postgres
   username: postgres
   password: 24680
jpa:
  show-sql: true
  database-platform: org.hibernate.dialect.postgresSQLDialect
  generate-ddl: true
  hibernate:
    ddl-auto: nome

  application:
    description: projeto criado para o bootcamp dio-santander
